# AURA Stress Test Suite (valid YAML)
test_cases:
  high_clutter:
    sim_time_s: 20
    targets:
      - id: 0
        path: [[-5, 0], [5, 0]]
        start_time_s: 0
        end_time_s: 20
    rf_clutter:
      count: 50
      rate_hz: 5.0
      x_range: [-10, 10]
      y_range: [-10, 10]

  high_density_crossing:
    sim_time_s: 15
    targets:
      - { id: 0, path: [[-4, -4], [4, 4]], start_time_s: 0, end_time_s: 15 }
      - { id: 1, path: [[-4,  4], [4,-4]], start_time_s: 0, end_time_s: 15 }
      - { id: 2, path: [[ 4,-4], [-4,4]], start_time_s: 0, end_time_s: 15 }
      - { id: 3, path: [[ 4, 4], [-4,-4]], start_time_s: 0, end_time_s: 15 }

  popup_targets:
    sim_time_s: 30
    targets:
      - { id: 0, path: [[-5, 2], [5, 2]], start_time_s: 0,  end_time_s: 30 }
      - { id: 1, path: [[-5,-2], [5,-2]], start_time_s: 5,  end_time_s: 15 }
      - { id: 2, path: [[ 5, 0], [-5,0]], start_time_s: 10, end_time_s: 25 }

  low_detection_prob:
    sim_time_s: 20
    targets:
      - { id: 0, path: [[-5, 0], [5, 0]], start_time_s: 0, end_time_s: 20 }
    nodes:
      mock_rf_node:
        ros__parameters:
          detection_probability: 0.5

  high_positional_noise:
    sim_time_s: 20
    targets:
      - { id: 0, path: [[-5, 0], [5, 0]], start_time_s: 0, end_time_s: 20 }
    nodes:
      mock_rf_node:
        ros__parameters:
          positional_noise_stddev: 0.5
