<<<<<<< HEAD
exclude: |
  ^ros2_ws/(build|install|log)/


repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks: [ { id: ruff, args: ["--fix"] }, { id: ruff-format } ]
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks: [ { id: black } ]
=======
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
>>>>>>> 725d9b9 (chore: cleanup workspace; single-source ROS pkg; tooling + lint fixes)
