name: CI
on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install pytest ruff black mypy

      - name: Lint
        run: |
          ruff check .
          black --check .
          mypy --ignore-missing-imports .

      - name: Pytests
        run: pytest -q

      - name: Smoke (optional)
        if: ${{ github.event_name != 'pull_request' }}  # reduce noise on forks
        run: |
          python tools/run_single.py --scenario scenarios/crossing_targets.yaml --out out/tmp/metrics.json || true
          if [ -f out/tmp/metrics.json ]; then
            python - <<'PY'
import json, sys, pathlib
p = pathlib.Path("out/tmp/metrics.json")
m = json.loads(p.read_text()) if p.exists() else {}
auc = m.get("auc", 0.0)
assert 0.0 <= auc <= 1.0, f"AUC out of range: {auc}"
print("AUC OK:", auc)
PY
          fi
