name: CI

on:
  push:
    branches: [ main, fix/**, feature/** ]
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pre-commit ruff black

      - name: Lint & format
        run: |
          ruff .
          ruff format --check .
          black --check .

      - name: Test
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q
