name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv pip install --system --no-cache -r requirements.txt
          # Core CI tools (ci_checks.py calls them)
          uv pip install --system --no-cache pytest ruff black mypy
          # Libs your tests/smoke may touch
          uv pip install --system --no-cache pandas motmetrics pyyaml
          # Type stubs for mypy
          uv pip install --system --no-cache types-requests types-PyYAML

      - name: Run unified checks
        env:
          # Make smoke non-fatal by default; flip to "1" to enforce
          AURA_CI_NO_SMOKE: "0"
          AURA_CI_STRICT_SMOKE: "0"
        run: |
          python .github/scripts/ci_checks.py