name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
<<<<<<< HEAD
  unit-and-fastpath:
=======
  lint_test:
>>>>>>> 5fdac64 (ci: docker-based smoke; fix Dockerfile; valid stress YAML; lint config; tighter .gitignore; clean index)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
<<<<<<< HEAD

      - name: Install deps (Python only)
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install pytest ruff black mypy pandas motmetrics pyyaml

=======
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install pytest ruff black mypy
>>>>>>> 5fdac64 (ci: docker-based smoke; fix Dockerfile; valid stress YAML; lint config; tighter .gitignore; clean index)
      - name: Lint
        run: |
          ruff check .
          black --check .
          mypy --ignore-missing-imports .
      - name: Pytests
        run: pytest -q

<<<<<<< HEAD
      - name: Fast-path smoke (no ROS)
        env:
          SKIP_ROS: "1"
          USE_AURA_EVALUATOR: "1"
        run: |
          set -euo pipefail
          python tools/run_single.py \
            --scenario scenarios/crossing_targets.yaml \
            --out out/tmp/metrics.json
          python - <<'PY'
import json
m = json.load(open("out/tmp/metrics.json"))
print("AUC:", m.get("auc"))
PY

  docker-smoke:
    # OPTIONAL: set `if:` to run only on main, or keep it for PRs too.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker
        run: docker build -t aura-ci .
      - name: Smoke inside Docker (ROS)
        run: |
          set -euo pipefail
          docker run --rm aura-ci /bin/bash -lc '
            source /opt/ros/humble/setup.bash || true
            cd /aura_ws
            python3 tools/run_single.py \
              --scenario scenarios/crossing_targets.yaml \
              --out out/tmp/metrics.json
            python3 - <<PY
import json
m = json.load(open("out/tmp/metrics.json"))
print("AUC:", m.get("auc"))
PY
=======
  docker_smoke:
    runs-on: ubuntu-latest
    needs: [lint_test]
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t aura-ci .
      - name: Smoke run (ROS inside container)
        run: |
          docker run --rm aura-ci /bin/bash -lc '
            set -e
            . /opt/ros/humble/setup.bash
            if [ -f "ros2_ws/install/local_setup.bash" ]; then . ros2_ws/install/local_setup.bash; fi
            python3 tools/run_single.py --scenario scenarios/crossing_targets.yaml --out out/tmp/metrics.json
            python3 - <<PY
import json, sys
m = json.load(open("out/tmp/metrics.json"))
assert 0.0 <= m.get("auc", 0.0) <= 1.0, "AUC out of range"
print("AUC OK:", m.get("auc"))
PY
>>>>>>> 5fdac64 (ci: docker-based smoke; fix Dockerfile; valid stress YAML; lint config; tighter .gitignore; clean index)
          '
