name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install pytest ruff black mypy

      - name: Lint
        run: |
          ruff check .
          black --check .
          mypy --ignore-missing-imports .

      - name: Pytests
        run: pytest -q

      - name: Smoke (optional)
        run: |
          python tools/run_single.py --scenario scenarios/crossing_targets.yaml --out out/tmp/metrics.json || true
          if [ -f out/tmp/metrics.json ]; then python -c "import json; m=json.load(open('out/tmp/metrics.json')); print('AUC:', m.get('auc'))"; fi
