name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unit-and-fastpath:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps (Python only)
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install pytest ruff black mypy pandas motmetrics pyyaml

      - name: Lint
        run: |
          ruff check .
          black --check .
          mypy --ignore-missing-imports .

      - name: Pytests
        run: pytest -q

      - name: Fast-path smoke (no ROS)
        env:
          SKIP_ROS: "1"
          USE_AURA_EVALUATOR: "1"
        run: |
          set -euo pipefail
          python tools/run_single.py \
            --scenario scenarios/crossing_targets.yaml \
            --out out/tmp/metrics.json
          python - <<'PY'
import json
m = json.load(open("out/tmp/metrics.json"))
print("AUC:", m.get("auc"))
PY

  docker-smoke:
    # OPTIONAL: set `if:` to run only on main, or keep it for PRs too.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker
        run: docker build -t aura-ci .
      - name: Smoke inside Docker (ROS)
        run: |
          set -euo pipefail
          docker run --rm aura-ci /bin/bash -lc '
            source /opt/ros/humble/setup.bash || true
            cd /aura_ws
            python3 tools/run_single.py \
              --scenario scenarios/crossing_targets.yaml \
              --out out/tmp/metrics.json
            python3 - <<PY
import json
m = json.load(open("out/tmp/metrics.json"))
print("AUC:", m.get("auc"))
PY
          '
