name: Docker Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  smoke:
    name: smoke
    runs-on: ubuntu-24.04
    timeout-minutes: 45

    env:
      SMOKE_METRICS: smoke/metrics.json
      MIN_MOTA: "0.80"
      SMOKE_CMD: python tools/oneclick_pipeline.py --config configs/smoke.yaml --metrics "$SMOKE_METRICS"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq (host)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Set up Docker Buildx
        id: b
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build aura:ci image (with cache)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ci-smoke
          tags: aura:ci
          outputs: type=docker
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run smoke (inside Docker)
        run: |
          docker run --rm \
            -e SMOKE_METRICS="$SMOKE_METRICS" \
            -e MIN_MOTA="$MIN_MOTA" \
            -v "$PWD:/work" -w /work \
            aura:ci bash -lc "$SMOKE_CMD"

      - name: Upload smoke artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: ${{ env.SMOKE_METRICS }}
          if-no-files-found: warn
