name: docker-smoke
on:
  pull_request:
  push:
    branches: [ main, "**" ]
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.jpg'
      - '**.gif'
      - '**.svg'
      - 'LICENSE'

permissions:
  contents: read

concurrency:
  group: docker-smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show Python
        run: python3 --version
      - name: Build image
        run: docker build -t aura:ci .
      - name: Smoke run (evaluator-only)
        run: |
          docker run --rm -v "$PWD":/work -w /work aura:ci bash -lc "
            python -m venv .venv && source .venv/bin/activate &&                 python -m pip install -U pip wheel setuptools &&                 if [ -f requirements.txt ]; then pip install -r requirements.txt; fi;                 if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install pytest; fi;                 mkdir -p out/tmp;                 if [ -f tools/run_single.py ]; then                   if [ -f scenarios/crossing_targets.yaml ]; then                     python tools/run_single.py --scenario scenarios/crossing_targets.yaml --out out/tmp/metrics.json;                   else                     python tools/run_single.py --out out/tmp/metrics.json;                   fi;                   test -s out/tmp/metrics.json;                 else                   echo 'tools/run_single.py not found' && exit 3;                 fi"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: |
            out/tmp/metrics.json
            out/**/report.html
          if-no-files-found: ignore
