name: Check THIRD_PARTY_NOTICES.md

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: licenses-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
<<<<<<< HEAD
          
          - name: Cache uv
  uses: actions/cache@v4
  with:
    path: ~/.cache/uv
    key: uv-${{ runner.os }}-${{ hashFiles('requirements.txt','requirements-dev.txt','uv.lock') }}


      - name: Create venv
        run: uv venv

      - name: Install deps and pip-licenses
        run: uv pip install -r requirements.txt -r requirements-dev.txt pip-licenses
=======

      - name: Install deps and pip-licenses
        run: |
          uv pip install -r requirements.txt -r requirements-dev.txt pip-licenses
>>>>>>> f034b75 (ci(licenses): auto-refresh and PR check for THIRD_PARTY_NOTICES.md)

      - name: Regenerate notices
        run: |
          PYTHONWARNINGS=ignore::DeprecationWarning uv run -m piplicenses --ignore-packages pip-licenses --with-authors --with-urls --format markdown > THIRD_PARTY_NOTICES.new.md

      - name: Verify up-to-date
        run: |
          test -f THIRD_PARTY_NOTICES.md
          diff -u THIRD_PARTY_NOTICES.md THIRD_PARTY_NOTICES.new.md
