name: Auto-refresh THIRD_PARTY_NOTICES.md

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"
  push:
    paths:
      - requirements.txt
      - requirements-dev.txt
      - uv.lock

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: licenses-auto-pr
  cancel-in-progress: true

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Create venv
        run: uv venv

      - name: Install deps and pip-licenses
        run: uv pip install -r requirements.txt -r requirements-dev.txt pip-licenses

      - name: Generate THIRD_PARTY_NOTICES.md
        run: |
          PYTHONWARNINGS=ignore::DeprecationWarning uv run -m piplicenses --ignore-packages pip-licenses --with-authors --with-urls --format markdown > THIRD_PARTY_NOTICES.md

      - name: Detect changes
        id: diff
        run: |
          git add THIRD_PARTY_NOTICES.md
          git diff --cached --quiet || echo "changed=1" >> "$GITHUB_OUTPUT"

      - name: Create PR with update
        if: steps.diff.outputs.changed == '1'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          BR="chore/auto-licenses-${GITHUB_RUN_ID}"
          git checkout -b "$BR"
          git commit -m "chore(licenses): refresh THIRD_PARTY_NOTICES.md"
          git push -u origin "$BR"
          gh pr create --title "chore(licenses): refresh THIRD_PARTY_NOTICES.md" --body "Automated refresh via CI" --base "main" --head "$BR"
